## Imports

In [ ]:
import pandas as pd
import numpy as np

## Loading Datasets

In [ ]:
# Loading Processed Dataset

model_df = pd.read_csv(
    "../data/processed/feature_engineered_loan_data.csv",
    low_memory=False
)

print(model_df.shape)
model_df.head()

(1303607, 142)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,...,dti_bucket,emp_length_clean,employment_stability,credit_history_years,inquiry_risk_bucket,delinquency_risk,loan_size_bucket,revol_bal_to_income,installment_to_income,credit_exposure_score
0,30000,30000,30000.0,36 months,22.35,1151.16,D,D5,5 years,mortgage,...,very_high_dti,5.0,short_term,6.920548,low_inquiry,no_delinquency,very_large,0.156030,0.138139,67.46
1,40000,40000,40000.0,60 months,16.14,975.71,C,C4,< 1 year,mortgage,...,very_high_dti,1.0,new,9.506849,low_inquiry,no_delinquency,very_large,0.777133,0.260189,115.03
2,20000,20000,20000.0,36 months,7.56,622.68,A,A3,10+ years,mortgage,...,moderate_dti,10.0,medium_term,19.843836,low_inquiry,no_delinquency,large,0.254160,0.074722,48.82
3,4500,4500,4500.0,36 months,11.31,147.99,B,B3,10+ years,rent,...,low_dti,10.0,medium_term,15.010959,low_inquiry,no_delinquency,small,0.116156,0.046127,19.94
4,8425,8425,8425.0,36 months,27.27,345.18,E,E5,3 years,mortgage,...,moderate_dti,3.0,short_term,21.180822,low_inquiry,no_delinquency,medium,0.081804,0.009205,78.07

In [ ]:
# Loading Risk Scores

risk_scores = pd.read_csv(
    "../outputs/predictions/risk_scores.csv"
)

print(risk_scores.shape)
risk_scores.head()

(260722, 3)

   actual  probability_default      risk_band
0       0             0.179421  Very Low Risk
1       0             0.156426  Very Low Risk
2       0             0.019365  Very Low Risk
3       0             0.353887       Low Risk
4       1             0.179403  Very Low Risk

In [ ]:
# Loading Threshold Metrics

threshold_df = pd.read_csv(
    "../outputs/predictions/threshold_metrics.csv"
)

print(threshold_df.shape)
threshold_df.head()

(18, 4)

   threshold  precision    recall  f1_score
0       0.10   0.249977  0.921309  0.393253
1       0.15   0.289778  0.812769  0.427233
2       0.20   0.332200  0.685215  0.447464
3       0.25   0.376049  0.552961  0.447661
4       0.30   0.419394  0.432000  0.425604

In [ ]:
# Loading Feature Importance

feature_importance = pd.read_csv(
    "../outputs/predictions/feature_importance.csv"
)

print(feature_importance.shape)
feature_importance.head()

(130, 2)

                feature  importance
0             sub_grade    0.209237
1                 grade    0.158195
2              int_rate    0.154966
3                  term    0.078853
4  income_to_loan_ratio    0.032125

In [ ]:
# Loading Portfolio Summary

portfolio_summary = pd.read_csv(
    "../outputs/predictions/portfolio_summary.csv"
)

print(portfolio_summary.shape)
portfolio_summary.head()

(4, 3)

   probability_default probability_default.1               actual
0                 mean                 count                 mean
1  0.10991807955440468                152781  0.10782099868439138
2  0.30533379778353864                 98558   0.3060329957994277
3   0.5864954455941597                  9383   0.6070553127997442

In [ ]:
# Loading Decision Default Rates

decision_default_rate = pd.read_csv(
    "../outputs/predictions/decision_default_rate.csv"
)

print(decision_default_rate.shape)
decision_default_rate.head()

(3, 1)

      actual
0  10.782100
1  30.603300
2  60.705531

In [ ]:
# Creating a Dashboard Export Folder

from pathlib import Path

export_dir = Path("../dashboard/data_exports")

export_dir.mkdir(
    parents=True,
    exist_ok=True
)

print("Export folder ready")

Export folder ready

In [ ]:
# Exporting Dashboard Dataset

dashboard_df = model_df.copy()

dashboard_df.to_csv(
    "../dashboard/data_exports/dashboard_dataset.csv",
    index=False
)

print("dashboard_dataset.csv exported")

dashboard_dataset.csv exported

In [ ]:
# Exporting Risk Scores


risk_scores.to_csv(
    "../dashboard/data_exports/risk_scores.csv",
    index=False
)

print("risk_scores.csv exported")

risk_scores.csv exported

In [ ]:
# Exporting Threshold Metrics

threshold_df.to_csv(
    "../dashboard/data_exports/threshold_metrics.csv",
    index=False
)

print("threshold_metrics.csv exported")

threshold_metrics.csv exported

In [ ]:
# Exporting Feature Importance

feature_importance.to_csv(
    "../dashboard/data_exports/feature_importance.csv",
    index=False
)

print("feature_importance.csv exported")

feature_importance.csv exported

In [ ]:
# Exporting Portfolio Summary

portfolio_summary.to_csv(
    "../dashboard/data_exports/portfolio_summary.csv",
    index=False
)

print("portfolio_summary.csv exported")

portfolio_summary.csv exported

In [ ]:
# Exporting Decision Default Rates

decision_default_rate.to_csv(
    "../dashboard/data_exports/decision_default_rate.csv",
    index=False
)

print("decision_default_rate.csv exported")

decision_default_rate.csv exported

In [ ]:
# Creating Risk Band Analysis

risk_band_analysis = (
    risk_scores.groupby('risk_band')['actual']
    .mean()
    * 100
).reset_index()

risk_band_analysis.columns = [
    'risk_band',
    'default_rate'
]

risk_band_analysis.head()

        risk_band  default_rate
0       High Risk     68.668076
1        Low Risk     28.050519
2     Medium Risk     48.016605
3  Very High Risk     93.679458
4   Very Low Risk     10.782100

In [ ]:
# Exporting Risk Band Analysis

risk_band_analysis.to_csv(
    "../dashboard/data_exports/risk_band_analysis.csv",
    index=False
)

print("risk_band_analysis.csv exported")

risk_band_analysis.csv exported

In [ ]:
# Verifying Exported Files

import os

export_path = "../dashboard/data_exports"

files = os.listdir(export_path)

print("Exported Files:")

for file in files:
    print(file)

Exported Files:
dashboard_dataset.csv
decision_default_rate.csv
feature_importance.csv
portfolio_summary.csv
risk_band_analysis.csv
risk_scores.csv
threshold_metrics.csv